# Generated by Django 5.1.4 on 2024-12-07 19:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todoitem_owner_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='Task',
        ),
    ]
